# GotToVote Config

country: "Ghana"
election_year: "2016"

registration_end_date: "13th August 2014"

api_key: "AIzaSyAwvkIls5mQybyp2R3g4FGiVetNdeVjUeE"
table_id: "1NMs_iAwYIZqdEBDVVuxA7nN4BQlvQwNAgevtPkYx"

google_analytics: 'UA-36749298-3'

# ------------------------------------------------------------------------------
# Jekyll Config

# Handling Reading
safe: true

# Conversion
highlighter: pygments
