# GotToVote Config

country: "Kenya"
election_year: "2017"

registration_end_date: "-"

api_key: "AIzaSyAwvkIls5mQybyp2R3g4FGiVetNdeVjUeE"
table_id: "1CSlnHwpe8qTpBAoSiwZAAH7PVbV0w9kRkvUypmXP"

google_analytics: 'UA-36749298-1'

# ------------------------------------------------------------------------------
# Jekyll Config

# Handling Reading
safe: true

# Conversion
highlighter: rouge
